#charvs properties
#Thu Feb 05 09:08:21 BRT 2026
FRAME_CHARVS_COMP_ARCHIVE_FOLDER=
FRAME_CHARVS_COMP_ARCHIVE_MAKE=false
FRAME_CHARVS_COMP_INPUT_FOLDER=
FRAME_CHARVS_COMP_OUTPUT_FOLDER=
FRAME_CHARVS_COMP_RECORD_FOLDER=
FRAME_CHARVS_COMP_RECORD_MAKE=false
FRAME_CHARVS_HEIGHT=260
FRAME_CHARVS_LEFT=960
FRAME_CHARVS_ON_TOP=false
FRAME_CHARVS_TOP=516
FRAME_CHARVS_WIDTH=439
