#charvs properties
#Sat Feb 21 09:06:14 BRT 2026
FRAME_CHARVS_COMP_ARCHIVE=
FRAME_CHARVS_COMP_ARCHIVE_ATOMIZAR=
FRAME_CHARVS_COMP_ARCHIVE_EXPLICAR=
FRAME_CHARVS_COMP_ARCHIVE_FOLDER=
FRAME_CHARVS_COMP_ARCHIVE_FOLDER_ATOMIZAR=
FRAME_CHARVS_COMP_ARCHIVE_MAKE=false
FRAME_CHARVS_COMP_ARCHIVE_MAKE_ATOMIZAR=false
FRAME_CHARVS_COMP_ARCHIVE_MAKE_EXPLICAR=false
FRAME_CHARVS_COMP_ARCHIVE_MAKE_QUESTIONAR=false
FRAME_CHARVS_COMP_ARCHIVE_QUESTIONAR=
FRAME_CHARVS_COMP_INPUT=
FRAME_CHARVS_COMP_INPUT_ATOMIZAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Programas\\Extração de Conhecimento
FRAME_CHARVS_COMP_INPUT_EXPLICAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Programas\\Extração de Conhecimento
FRAME_CHARVS_COMP_INPUT_FOLDER=
FRAME_CHARVS_COMP_INPUT_FOLDER_ATOMIZAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Programas\\Extração de Conhecimento
FRAME_CHARVS_COMP_INPUT_FOLDER_EXPLICAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Programas\\Extração de Conhecimento
FRAME_CHARVS_COMP_INPUT_FOLDER_QUESTIONAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Programas\\Extração de Conhecimento
FRAME_CHARVS_COMP_INPUT_QUESTIONAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Programas\\Extração de Conhecimento
FRAME_CHARVS_COMP_OUTPUT=
FRAME_CHARVS_COMP_OUTPUT_ATOMIZAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Conhecimento\\- Funcional\\- Direito\\- Direito Penal\\- Lei dos Delitos Informáticos
FRAME_CHARVS_COMP_OUTPUT_EXPLICAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Conhecimento\\- Funcional\\- Direito\\- Direito Penal\\- Lei dos Delitos Informáticos
FRAME_CHARVS_COMP_OUTPUT_FOLDER=
FRAME_CHARVS_COMP_OUTPUT_FOLDER_ATOMIZAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Conhecimento\\- Funcional\\- Direito\\- Direito Penal\\- Lei dos Delitos Informáticos
FRAME_CHARVS_COMP_OUTPUT_FOLDER_EXPLICAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Conhecimento\\- Funcional\\- Direito\\- Direito Penal\\- Lei dos Delitos Informáticos
FRAME_CHARVS_COMP_OUTPUT_FOLDER_QUESTIONAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Conhecimento\\- Funcional\\- Direito\\- Direito Penal\\- Lei dos Delitos Informáticos
FRAME_CHARVS_COMP_OUTPUT_NAME_ATOMIZAR=
FRAME_CHARVS_COMP_OUTPUT_NAME_EXPLICAR=
FRAME_CHARVS_COMP_OUTPUT_NAME_QUESTIONAR=+ Agravantes por Divulgação de Dados, Vítimas Qualificadas e Regime da Ação Penal
FRAME_CHARVS_COMP_OUTPUT_QUESTIONAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Conhecimento\\- Funcional\\- Direito\\- Direito Penal\\- Lei dos Delitos Informáticos
FRAME_CHARVS_COMP_PERFIL=Atomizar
FRAME_CHARVS_COMP_PERFIL_LIST=-|-Atomizar-|-Questionar-|-Explicar
FRAME_CHARVS_COMP_RECORD=
FRAME_CHARVS_COMP_RECORD_ATOMIZAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Conhecimento\\- Funcional\\- Direito\\- Direito Penal\\- Lavagem de Dinheiro\\+ Tipificação Penal, Penas e Modalidades de Ocultação e Dissimulação de Capitais.md
FRAME_CHARVS_COMP_RECORD_EXPLICAR=
FRAME_CHARVS_COMP_RECORD_FILE=
FRAME_CHARVS_COMP_RECORD_FILE_ATOMIZAR=C\:\\Users\\Adm\\OneDrive\\Documentos\\Conhecimento\\- Funcional\\- Direito\\- Direito Penal\\- Lavagem de Dinheiro\\+ Tipificação Penal, Penas e Modalidades de Ocultação e Dissimulação de Capitais.md
FRAME_CHARVS_COMP_RECORD_FILE_EXPLICAR=
FRAME_CHARVS_COMP_RECORD_MAKE=false
FRAME_CHARVS_COMP_RECORD_MAKE_ATOMIZAR=true
FRAME_CHARVS_COMP_RECORD_MAKE_EXPLICAR=false
FRAME_CHARVS_COMP_RECORD_MAKE_QUESTIONAR=false
FRAME_CHARVS_COMP_RECORD_QUESTIONAR=
FRAME_CHARVS_HEIGHT=278
FRAME_CHARVS_LEFT=719
FRAME_CHARVS_ON_TOP=false
FRAME_CHARVS_TOP=360
FRAME_CHARVS_WIDTH=537
FRAME_REPLACES_HEIGHT=278
FRAME_REPLACES_LEFT=719
FRAME_REPLACES_ON_TOP=false
FRAME_REPLACES_TOP=86
FRAME_REPLACES_WIDTH=536
FRAME_REPLACE_HEIGHT=164
FRAME_REPLACE_LEFT=722
FRAME_REPLACE_ON_TOP=false
FRAME_REPLACE_TOP=196
FRAME_REPLACE_WIDTH=528
FRAME_SETUP_COMP_APPLY_REPLACES_LIST=false
FRAME_SETUP_COMP_APPLY_REPLACES_LIST_ATOMIZAR=true
FRAME_SETUP_COMP_APPLY_REPLACES_LIST_EXPLICAR=true
FRAME_SETUP_COMP_APPLY_REPLACES_LIST_QUESTIONAR=false
FRAME_SETUP_COMP_INSERT_AT_BEGIN=
FRAME_SETUP_COMP_INSERT_AT_BEGIN_ATOMIZAR=---\\ncreated-at\: ${dateMach}\\nrevised-on\: ${dateMach}\\nrevised-count\: 1\\n--- 
FRAME_SETUP_COMP_INSERT_AT_BEGIN_EXPLICAR=
FRAME_SETUP_COMP_INSERT_AT_BEGIN_QUESTIONAR=
FRAME_SETUP_COMP_INSERT_AT_END=
FRAME_SETUP_COMP_INSERT_AT_END_ATOMIZAR=\\n\\n*Refs\:* ${Refs}
FRAME_SETUP_COMP_INSERT_AT_END_EXPLICAR=\\n\\n*Refs\:* ${Refs}
FRAME_SETUP_COMP_INSERT_AT_END_QUESTIONAR=
FRAME_SETUP_COMP_MULTIPLE_MINIMUM_SIZE=0
FRAME_SETUP_COMP_MULTIPLE_MINIMUM_SIZE_ATOMIZAR=300
FRAME_SETUP_COMP_MULTIPLE_MINIMUM_SIZE_EXPLICAR=0
FRAME_SETUP_COMP_MULTIPLE_MINIMUM_SIZE_QUESTIONAR=0
FRAME_SETUP_COMP_NAME_EXTENSION=
FRAME_SETUP_COMP_NAME_EXTENSION_ATOMIZAR=.md
FRAME_SETUP_COMP_NAME_EXTENSION_EXPLICAR=.txt
FRAME_SETUP_COMP_NAME_EXTENSION_QUESTIONAR=.csv
FRAME_SETUP_COMP_NAME_NUMBERED_PREFIX=
FRAME_SETUP_COMP_NAME_NUMBERED_PREFIX_ATOMIZAR=
FRAME_SETUP_COMP_NAME_NUMBERED_PREFIX_EXPLICAR=
FRAME_SETUP_COMP_NAME_NUMBERED_PREFIX_QUESTIONAR=
FRAME_SETUP_COMP_NAME_NUMBERED_SIZE=0
FRAME_SETUP_COMP_NAME_NUMBERED_SIZE_ATOMIZAR=0
FRAME_SETUP_COMP_NAME_NUMBERED_SIZE_EXPLICAR=0
FRAME_SETUP_COMP_NAME_NUMBERED_SIZE_QUESTIONAR=0
FRAME_SETUP_COMP_NAME_NUMBERED_SUFFIX=
FRAME_SETUP_COMP_NAME_NUMBERED_SUFFIX_ATOMIZAR=
FRAME_SETUP_COMP_NAME_NUMBERED_SUFFIX_EXPLICAR=
FRAME_SETUP_COMP_NAME_NUMBERED_SUFFIX_QUESTIONAR=
FRAME_SETUP_COMP_ON_CLIPBOARD_NEW_TEXT=0
FRAME_SETUP_COMP_ON_CLIPBOARD_NEW_TEXT_ATOMIZAR=0
FRAME_SETUP_COMP_ON_CLIPBOARD_NEW_TEXT_EXPLICAR=1
FRAME_SETUP_COMP_ON_CLIPBOARD_NEW_TEXT_QUESTIONAR=1
FRAME_SETUP_COMP_ON_NAMING=0
FRAME_SETUP_COMP_ON_NAMING_ATOMIZAR=1
FRAME_SETUP_COMP_ON_NAMING_EXPLICAR=1
FRAME_SETUP_COMP_ON_NAMING_QUESTIONAR=0
FRAME_SETUP_COMP_ON_RECORD=0
FRAME_SETUP_COMP_ON_RECORD_ATOMIZAR=1
FRAME_SETUP_COMP_ON_RECORD_EXISTS=0
FRAME_SETUP_COMP_ON_RECORD_EXISTS_ATOMIZAR=1
FRAME_SETUP_COMP_ON_RECORD_EXISTS_EXPLICAR=0
FRAME_SETUP_COMP_ON_RECORD_EXISTS_QUESTIONAR=0
FRAME_SETUP_COMP_ON_RECORD_EXPLICAR=0
FRAME_SETUP_COMP_ON_RECORD_QUESTIONAR=0
FRAME_SETUP_COMP_ON_SAVE=0
FRAME_SETUP_COMP_ON_SAVE_EXISTS=0
FRAME_SETUP_COMP_ON_SAVE_EXISTS_ATOMIZAR=0
FRAME_SETUP_COMP_ON_SAVE_EXISTS_EXPLICAR=0
FRAME_SETUP_COMP_ON_SAVE_EXISTS_QUESTIONAR=0
FRAME_SETUP_COMP_RECORD_PREFIX=
FRAME_SETUP_COMP_RECORD_PREFIX_ATOMIZAR=[[
FRAME_SETUP_COMP_RECORD_PREFIX_EXPLICAR=
FRAME_SETUP_COMP_RECORD_PREFIX_QUESTIONAR=
FRAME_SETUP_COMP_RECORD_SUFFIX=
FRAME_SETUP_COMP_RECORD_SUFFIX_ATOMIZAR=]]
FRAME_SETUP_COMP_RECORD_SUFFIX_EXPLICAR=
FRAME_SETUP_COMP_RECORD_SUFFIX_QUESTIONAR=
FRAME_SETUP_COMP_REPLACE_VARS_HOLDERS=false
FRAME_SETUP_COMP_REPLACE_VARS_HOLDERS_ATOMIZAR=true
FRAME_SETUP_COMP_REPLACE_VARS_HOLDERS_EXPLICAR=true
FRAME_SETUP_COMP_REPLACE_VARS_HOLDERS_QUESTIONAR=false
FRAME_SETUP_COMP_SAVE_MULTIPLE_DIVIDER=
FRAME_SETUP_COMP_SAVE_MULTIPLE_DIVIDER_ATOMIZAR=\\-\\-\\-
FRAME_SETUP_COMP_SAVE_MULTIPLE_DIVIDER_EXPLICAR=
FRAME_SETUP_COMP_SAVE_MULTIPLE_DIVIDER_QUESTIONAR=
FRAME_SETUP_COMP_STRIP_FIRST_LINES=0
FRAME_SETUP_COMP_STRIP_FIRST_LINES_ATOMIZAR=1
FRAME_SETUP_COMP_STRIP_FIRST_LINES_EXPLICAR=0
FRAME_SETUP_COMP_STRIP_FIRST_LINES_QUESTIONAR=0
FRAME_SETUP_COMP_TRIM_FINAL_TEXT=false
FRAME_SETUP_COMP_TRIM_FINAL_TEXT_ATOMIZAR=true
FRAME_SETUP_COMP_TRIM_FINAL_TEXT_EXPLICAR=true
FRAME_SETUP_COMP_TRIM_FINAL_TEXT_QUESTIONAR=true
FRAME_SETUP_HEIGHT=546
FRAME_SETUP_LEFT=723
FRAME_SETUP_ON_TOP=false
FRAME_SETUP_TOP=89
FRAME_SETUP_WIDTH=416
