package br.com.pointel.charvs;

/**
 *
 * @author emuvi
 */
public enum Event {
    
    BEFORE_BUFFER_CLEAR,
    AFTER_BUFFER_CLEAR,
    BEFORE_BUFFER_APPEND,
    AFTER_BUFFER_APPEND,
    BEFORE_ORIGIN_SELECT,
    AFTER_ORIGIN_SELECT,
    BEFORE_ORIGIN_OPEN,
    AFTER_ORIGIN_OPEN,
    BEFORE_ORIGIN_FILES_UPDATE,
    AFTER_ORIGIN_FILES_UPDATE,
    BEFORE_ORIGIN_FILE_OPEN,
    AFTER_ORIGIN_FILE_OPEN,
    BEFORE_ORIGIN_FILES_FIRST,
    AFTER_ORIGIN_FILES_FIRST,
    BEFORE_ORIGIN_FILES_PRIOR,
    AFTER_ORIGIN_FILES_PRIOR,
    BEFORE_ORIGIN_FILES_NEXT,
    AFTER_ORIGIN_FILES_NEXT,
    BEFORE_ORIGIN_FILES_SWITCH,
    AFTER_ORIGIN_FILES_SWITCH,
    BEFORE_ORIGIN_FILE_LOAD,
    AFTER_ORIGIN_FILE_LOAD,
    BEFORE_ORIGIN_FILE_INSERT,
    AFTER_ORIGIN_FILE_INSERT,
    BEFORE_DESTINY_SELECT,
    AFTER_DESTINY_SELECT,
    BEFORE_DESTINY_OPEN,
    AFTER_DESTINY_OPEN,
    BEFORE_DESTINY_FILE_SAVE,
    AFTER_DESTINY_FILE_SAVE,
    BEFORE_DESTINY_FILE_OPEN,
    AFTER_DESTINY_FILE_OPEN,
    
}
